apiVersion: v1
kind: ReplicationController
metadata:
        name: kubia
spec:
        replicas: 1
        selector:
                app: web
                env: test
        template:
                metadata:
                        labels:
                                app: web
                                env: test
                spec:
                        containers:
                                - name: kubia
                                  image: highlighter9/kubia
                                  ports:
                                  - containerPort: 8080
